version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emumba_qor
      MYSQL_USER: d2s
      MYSQL_PASSWORD: d2s_1234
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: scripts/app.py
      DATABASE_URL: mysql+pymysql://d2s:d2s_1234@db/emumba_qor
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
