# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
  
#   pull_request:
#     branches:
#       - main
  
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.10'

#     - name: Install dependencies
#       run: |
#         python -m venv venv
#         source venv/bin/activate
#         pip install -r scripts/requirements.txt

#   test:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Install Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '20'

#     - name: Install Newman
#       run: npm install -g newman

#     - name: Run Newman tests
#       run: newman run postman/Project.postman_collection2.json

#   deploy:
#     runs-on: ubuntu-latest
#     needs: test

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Docker
#       uses: docker/setup-buildx-action@v3

#     - name: Install Docker Compose
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y docker-compose

#     - name: Run Docker Compose
#       run: |
#         docker-compose up -d

#     - name: Verify Deployment
#       run: |
#         # Add a wait or check for the service to be ready
#         sleep 5
#         curl -f http://localhost:5000/ || exit 1










# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
  
#   pull_request:
#     branches:
#       - main
  
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.10'

#     - name: Install dependencies
#       run: |
#         python -m venv venv
#         source venv/bin/activate
#         pip install -r scripts/requirements.txt

#     - name: Set up Docker
#       uses: docker/setup-buildx-action@v3

#     - name: Install Docker Compose
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y docker-compose

#     - name: Build Docker images
#       run: |
#         docker-compose build

#     - name: Run Docker Compose
#       run: |
#         docker-compose up -d

#   test:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Install Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '20'

#     - name: Install Newman
#       run: npm install -g newman

#     - name: Run Newman tests
#       run: newman run postman/Project.postman_collection.json

#   deploy:
#     runs-on: ubuntu-latest
#     needs: test

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Install Docker Compose
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y docker-compose

#     - name: Run Docker Compose
#       run: |
#         docker-compose up -d

#     - name: Verify Deployment
#       run: |
#         # Add a wait or check for the service to be ready
#         sleep 5
#         curl -f http://localhost:5000/ || exit 1
















# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
  
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.10'

#     - name: Install dependencies
#       run: |
#         python -m venv venv
#         source venv/bin/activate
#         pip install -r scripts/requirements.txt

#     - name: Set up Docker
#       uses: docker/setup-buildx-action@v3

#     - name: Install Docker Compose
#       run: sudo apt-get update && sudo apt-get install -y docker-compose

#     - name: Build Docker images
#       run: docker-compose build

#     - name: Run Docker Compose
#       run: docker-compose up -d

#     - name: Wait for services to be ready
#       run: |
#         # Adjust sleep duration as needed
#         sleep 10
#         curl -f http://localhost:5000/ || exit 1

#   test:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Install Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '20'

#     - name: Install Newman
#       run: npm install -g newman

#     - name: Run Newman tests
#       run: newman run postman/Project.postman_collection.json

#   merge:
#     runs-on: ubuntu-latest
#     needs: test
#     if: github.event_name == 'pull_request' && github.event.action == 'opened'

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Install GitHub CLI
#       run: sudo apt-get install gh

#     - name: Authenticate GitHub CLI
#       run: gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}

#     - name: Merge pull request
#       run: |
#         pr_number=$(gh pr list --state open --json number -q '.[0].number')
#         gh pr merge $pr_number --merge

#   deploy:
#     runs-on: ubuntu-latest
#     needs: merge

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Docker
#       uses: docker/setup-buildx-action@v3

#     - name: Build Docker images
#       run: docker-compose build

#     - name: Run Docker Compose
#       run: docker-compose up -d

#     - name: Wait for services to be ready
#       run: |
#         # Adjust sleep duration as needed
#         sleep 10
#         curl -f http://localhost:5000/ || exit 1














name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r scripts/requirements.txt

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Build Docker images
      run: docker-compose build

    - name: Run Docker Compose
      run: docker-compose up -d

    # - name: Wait for services to be ready
    #   run: |
    #     # Adjust sleep duration as needed
    #     sleep 10
    #     curl -f http://localhost:5000/ || exit 1

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Newman tests
      run: newman run postman/Project.postman_collection2.json
    
    - name: Run Docker Compose
      run: docker-compose down

  merge:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' && github.event.action == 'opened'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate GitHub CLI
      run: gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}

    - name: Merge pull request
      run: |
        pr_number=$(gh pr list --state open --json number -q '.[0].number')
        gh pr merge $pr_number --merge

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: docker-compose build

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Wait for services to be ready
      run: |
        # Adjust sleep duration as needed
        sleep 10
        curl -f http://localhost:5000/ || exit 1
