# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
  
#   pull_request:
#     branches:
#       - main
  
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: '3.10'

#     - name: Install dependencies
#       run: |
#         python -m venv venv
#         source venv/bin/activate
#         pip install -r scripts/requirements.txt

#   test:
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Install Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '20'

#     - name: Install Newman
#       run: npm install -g newman

#     - name: Run Newman tests
#       run: newman run postman/Project.postman_collection2.json

#   deploy:
#     runs-on: ubuntu-latest
#     needs: test

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set up Docker
#       uses: docker/setup-buildx-action@v3

#     - name: Install Docker Compose
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y docker-compose

#     - name: Run Docker Compose
#       run: |
#         docker-compose up -d

#     - name: Verify Deployment
#       run: |
#         # Add a wait or check for the service to be ready
#         sleep 5
#         curl -f http://localhost:5000/ || exit 1
















name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r scripts/requirements.txt

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker images
      run: |
        docker-compose build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Newman tests
      run: newman run postman/Project.postman_collection2.json

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Run Docker Compose
      run: |
        docker-compose up -d

    - name: Verify Deployment
      run: |
        # Add a wait or check for the service to be ready
        sleep 5
        curl -f http://localhost:5000/ || exit 1
