name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r scripts/requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Newman tests
      run: newman run postman/Project.postman_collection2.json

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run Docker Compose
      run: |
        docker-compose up -d

    - name: Verify Deployment
      run: |
        # Add a wait or check for the service to be ready
        sleep 5
        curl -f https://e3c7-203-99-184-187.ngrok-free.app// || exit 1
